export default [
  {
    description: "Energia elétrica",
    amount: "100.25",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-10",
  },

  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-23",
  },
  {
    description: "Compras do mês",
    amount: "625.78",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-01-23",
  },
  {
    description: "Blusa",
    amount: "95.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-01-23",
  },
  {
    description: "Energia elétrica",
    amount: "100.25",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-10",
  },
  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-15",
  },

  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-23",
  },
  {
    description: "Compras do mês",
    amount: "625.78",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-02-23",
  },
  {
    description: "Blusa",
    amount: "95.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-02-23",
  },
  {
    description: "Energia elétrica",
    amount: "100.25",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-10",
  },
  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-23",
  },

  {
    description: "Compras do mês",
    amount: "625.78",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-03-23",
  },
  {
    description: "Blusa",
    amount: "40.56",
    type: "saída",
    frequency: "eventual",
    date: "2020-03-23",
  },
  {
    description: "Energia elétrica",
    amount: "100.25",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-10",
  },
  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-23",
  },

  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-04-23",
  },
  {
    description: "Blusa",
    amount: "40.56",
    type: "saída",
    frequency: "eventual",
    date: "2020-04-23",
  },

  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-23",
  },
  {
    description: "Compras do mês",
    amount: "625.78",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-05-23",
  },
  {
    description: "Blusa",
    amount: "40.56",
    type: "saída",
    frequency: "eventual",
    date: "2020-05-23",
  },
  {
    description: "Energia elétrica",
    amount: "100.25",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-10",
  },
  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-23",
  },
  {
    description: "Compras do mês",
    amount: "625.78",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-06-23",
  },

  {
    description: "Energia elétrica",
    amount: "100.25",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-10",
  },
  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-23",
  },

  {
    description: "Compras do mês",
    amount: "625.78",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-07-23",
  },
  {
    description: "Blusa",
    amount: "40.56",
    type: "saída",
    frequency: "eventual",
    date: "2020-07-23",
  },
  {
    description: "Energia elétrica",
    amount: "100.25",
    type: "saída",
    frequency: "recorrente",
    date: "2020-08-10",
  },

  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-08-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-08-23",
  },
  {
    description: "Compras do mês",
    amount: "625.78",
    type: "saída",
    frequency: "recorrente",
    date: "2020-08-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-08-23",
  },
  {
    description: "Blusa",
    amount: "40.56",
    type: "saída",
    frequency: "eventual",
    date: "2020-08-23",
  },

  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2020-09-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-09-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-09-23",
  },

  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-09-23",
  },
  {
    description: "Blusa",
    amount: "40.56",
    type: "saída",
    frequency: "eventual",
    date: "2020-09-23",
  },
  {
    description: "Energia elétrica",
    amount: "100.25",
    type: "saída",
    frequency: "recorrente",
    date: "2020-10-10",
  },
  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2020-10-15",
  },

  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-10-23",
  },
  {
    description: "Compras do mês",
    amount: "625.78",
    type: "saída",
    frequency: "recorrente",
    date: "2020-10-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-10-23",
  },
  {
    description: "Blusa",
    amount: "40.56",
    type: "saída",
    frequency: "eventual",
    date: "2020-10-23",
  },
  {
    description: "Energia elétrica",
    amount: "100.25",
    type: "saída",
    frequency: "recorrente",
    date: "2020-11-11",
  },
  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2020-11-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-11-23",
  },

  {
    description: "Compras do mês",
    amount: "625.78",
    type: "saída",
    frequency: "recorrente",
    date: "2020-11-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-11-23",
  },
  {
    description: "Blusa",
    amount: "40.56",
    type: "saída",
    frequency: "eventual",
    date: "2020-11-23",
  },
  {
    description: "Energia elétrica",
    amount: "100.25",
    type: "saída",
    frequency: "recorrente",
    date: "2020-12-12",
  },

  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-12-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-12-23",
  },
  {
    description: "Compras do mês",
    amount: "625.78",
    type: "saída",
    frequency: "recorrente",
    date: "2020-12-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-12-23",
  },
  {
    description: "Blusa",
    amount: "95.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-12-23",
  },
  {
    description: "Energia elétrica",
    amount: "150.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-01-01",
  },
  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-01-15",
  },
  {
    description: "Telefone",
    amount: "138.5",
    type: "saída",
    frequency: "recorrente",
    date: "2021-01-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-01-23",
  },
  {
    description: "Compras do mês",
    amount: "746.98",
    type: "saída",
    frequency: "recorrente",
    date: "2021-01-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-01-23",
  },
  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-02-15",
  },
  {
    description: "Telefone",
    amount: "138.5",
    type: "saída",
    frequency: "recorrente",
    date: "2021-02-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-02-23",
  },
  {
    description: "Compras do mês",
    amount: "746.98",
    type: "saída",
    frequency: "recorrente",
    date: "2021-02-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-02-23",
  },
  {
    description: "Blusa",
    amount: "95.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-02-23",
  },
  {
    description: "Energia elétrica",
    amount: "150.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-03-03",
  },
  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-03-15",
  },
  {
    description: "Telefone",
    amount: "138.5",
    type: "saída",
    frequency: "recorrente",
    date: "2021-03-23",
  },
  {
    description: "Compras do mês",
    amount: "746.98",
    type: "saída",
    frequency: "recorrente",
    date: "2021-03-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-03-23",
  },
  {
    description: "Blusa",
    amount: "95.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-03-23",
  },
  {
    description: "Energia elétrica",
    amount: "150.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-04-10",
  },
  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-04-15",
  },
  {
    description: "Telefone",
    amount: "138.5",
    type: "saída",
    frequency: "recorrente",
    date: "2021-04-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-04-23",
  },

  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-04-23",
  },
  {
    description: "Blusa",
    amount: "95.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-04-23",
  },

  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-05-15",
  },
  {
    description: "Telefone",
    amount: "138.5",
    type: "saída",
    frequency: "recorrente",
    date: "2021-05-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-05-23",
  },
  {
    description: "Compras do mês",
    amount: "746.98",
    type: "saída",
    frequency: "recorrente",
    date: "2021-05-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-05-23",
  },
  {
    description: "Blusa",
    amount: "95.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-05-23",
  },
  {
    description: "Energia elétrica",
    amount: "150.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-06-10",
  },
  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-06-15",
  },
  {
    description: "Telefone",
    amount: "138.5",
    type: "saída",
    frequency: "recorrente",
    date: "2021-06-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-06-23",
  },
  {
    description: "Compras do mês",
    amount: "746.98",
    type: "saída",
    frequency: "recorrente",
    date: "2021-06-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-06-23",
  },

  {
    description: "Energia elétrica",
    amount: "150.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-07-10",
  },
  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-07-15",
  },
  {
    description: "Telefone",
    amount: "138.5",
    type: "saída",
    frequency: "recorrente",
    date: "2021-07-23",
  },

  {
    description: "Compras do mês",
    amount: "746.98",
    type: "saída",
    frequency: "recorrente",
    date: "2021-07-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-07-23",
  },
  {
    description: "Blusa",
    amount: "95.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-07-23",
  },
  {
    description: "Energia elétrica",
    amount: "150.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-08-10",
  },

  {
    description: "Telefone",
    amount: "138.5",
    type: "saída",
    frequency: "recorrente",
    date: "2021-08-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-08-23",
  },
  {
    description: "Compras do mês",
    amount: "746.98",
    type: "saída",
    frequency: "recorrente",
    date: "2021-08-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-08-23",
  },
  {
    description: "Blusa",
    amount: "95.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-08-23",
  },

  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-09-15",
  },
  {
    description: "Telefone",
    amount: "138.5",
    type: "saída",
    frequency: "recorrente",
    date: "2021-09-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-09-23",
  },

  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-09-23",
  },
  {
    description: "Blusa",
    amount: "95.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-09-23",
  },
  {
    description: "Energia elétrica",
    amount: "150.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-10-10",
  },
  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-10-15",
  },

  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-10-23",
  },
  {
    description: "Compras do mês",
    amount: "746.98",
    type: "saída",
    frequency: "recorrente",
    date: "2021-10-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-10-23",
  },
  {
    description: "Blusa",
    amount: "95.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-10-23",
  },
  {
    description: "Energia elétrica",
    amount: "150.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-11-11",
  },
  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-11-15",
  },
  {
    description: "Telefone",
    amount: "138.5",
    type: "saída",
    frequency: "recorrente",
    date: "2021-11-23",
  },

  {
    description: "Compras do mês",
    amount: "746.98",
    type: "saída",
    frequency: "recorrente",
    date: "2021-11-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-11-23",
  },
  {
    description: "Blusa",
    amount: "95.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-11-23",
  },
  {
    description: "Energia elétrica",
    amount: "150.55",
    type: "saída",
    frequency: "recorrente",
    date: "2021-12-12",
  },

  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2021-12-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2021-12-23",
  },
  {
    description: "Compras do mês",
    amount: "746.98",
    type: "saída",
    frequency: "recorrente",
    date: "2021-12-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-12-23",
  },
  {
    description: "Blusa",
    amount: "95.70",
    type: "saída",
    frequency: "eventual",
    date: "2021-12-23",
  },
];
